# Generated by Django 4.2 on 2023-04-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='techologia',
            new_name='technology',
        ),
    ]
